# Generated by Django 3.2.2 on 2021-07-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
    ]
