# Generated by Django 3.2.2 on 2021-07-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('cart', '0004_auto_20210708_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ourCart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='ourCartitems',
            new_name='Cartitems',
        ),
    ]
