# Generated by Django 3.2.2 on 2021-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
        ('cart', '0005_auto_20210708_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='itemVariation',
            field=models.ManyToManyField(blank=True, to='store.productVariation'),
        ),
    ]
